# Generated by Django 5.0.7 on 2024-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0004_alter_slider_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_btn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='slides/'),
        ),
    ]
